### ISSUE TITLE
Can't find a guideline on how to contribute?

### ISSUE THREAD

**Issue by golden88** [tyberious-1/codebuddiesMUD#14]
Reading the `README.md`, I can't figure out what would be my first steps to get up and running to tackle issues in your project. It would be great to include some kind of `CONTRIBUTING.md`, which showcases a way on how to get the project running on a local machine in order to solve issues.

**Comment by angelocordon** [comment]
Hi @golden88 - we just updated the README docs yesterday and you can see the contributing guidelines here: https://github.com/codebuddies/dungeonbuddies#contribution-guidelines. 

Let me know if you need more help getting up and running!
