### ISSUE TITLE
Account data model

### ISSUE THREAD

**Issue by jtkaufman737** [tyberious-1/codebuddiesMUD#4]
Ok folks I'm going to just toss some ideas out here. This won't be a huge data set so I don't know that we need to get too fancy.

I'm thinking the breakout might be something like...
- **email:** varchar
- **account ID**: primary key & UUID string (*Maybe this should be foreign key to User table?) 
- **password**: hashed val (? Who knows, maybe want to let it all run through Auth0 or something. Actually, using something like that would significantly impact all this other stuff lol) 
- **account lockout field**: bool 

What else...am I missing stuff?

**Comment by angelocordon** [comment]
@jtkaufman737 - wondering if this issue and #5 should be merged as I see these two issues really more connected together as a `User` model (from a rails perspective). My thoughts:

A `User` should have a unique email address and we can probably/should index a UUID. 

From the authentication side of things, for simplicity, we could use [Devise](https://github.com/plataformatec/devise). There's also [Clearance](https://github.com/thoughtbot/clearance), but I have not worked with this before (though it might be a great learning opportunity). Auth0 feels a bit... overkill? Unless if they have a simpler authentication method similar to Devise or Clearance.

Not sure if we need an account lockout - seems more complicated than necessary currently, though open for implementing it at a later time if we deem it to be important enough.
